# coding: utf-8
# This file is generated by generate_existing_node_stub.py.
from __future__ import annotations

from typing import Literal, Self, overload

from .modifier import ModifierManager
from .operator.node import NodesKeyframeManager
from ._versioned_accessors import (
    _ExistingNodeAccessorCommon,
    _ExistingNodeAccessorMaya2025,
    _ExistingNodeAccessorMaya2026,
    _ExistingNodeAccessorMaya2027,
    _NodeCreatorCommon,
    _NodeCreatorMaya2025,
    _NodeCreatorMaya2026,
    _NodeCreatorMaya2027,
)

class Nodes:
    @overload
    def __new__(
        cls,
        modifier_manager: ModifierManager | None = None,
        *,
        namespace: str | None = None,
        typing_maya_version: Literal["2025"],
    ) -> _NodesMaya2025: ...
    @overload
    def __new__(
        cls,
        modifier_manager: ModifierManager | None = None,
        *,
        namespace: str | None = None,
        typing_maya_version: Literal["2026"],
    ) -> _NodesMaya2026: ...
    @overload
    def __new__(
        cls,
        modifier_manager: ModifierManager | None = None,
        *,
        namespace: str | None = None,
        typing_maya_version: Literal["2027"],
    ) -> _NodesMaya2027: ...
    @overload
    def __new__(
        cls,
        modifier_manager: ModifierManager | None = None,
        *,
        namespace: str | None = None,
        typing_maya_version: None = None,
    ) -> Nodes: ...
    def __init__(
        self,
        modifier_manager: ModifierManager | None = None,
        *,
        namespace: str | None = None,
        typing_maya_version: Literal["2025", "2026", "2027"] | None = None,
    ) -> None: ...
    @property
    def modifier_manager(self) -> ModifierManager: ...
    @property
    def namespace(self) -> str | None: ...
    def set_namespace(self, namespace: str | None) -> Self: ...
    @property
    def keyframes(self) -> NodesKeyframeManager: ...
    @property
    def create(self) -> _NodeCreatorCommon: ...
    @property
    def existing(self) -> _ExistingNodeAccessorCommon: ...

class _NodesMaya2025(Nodes):
    @property
    def create(self) -> _NodeCreatorMaya2025: ...
    @property
    def existing(self) -> _ExistingNodeAccessorMaya2025: ...

class _NodesMaya2026(Nodes):
    @property
    def create(self) -> _NodeCreatorMaya2026: ...
    @property
    def existing(self) -> _ExistingNodeAccessorMaya2026: ...

class _NodesMaya2027(Nodes):
    @property
    def create(self) -> _NodeCreatorMaya2027: ...
    @property
    def existing(self) -> _ExistingNodeAccessorMaya2027: ...
