from __future__ import annotations

from abc import abstractmethod
from typing import ClassVar, Generic, Self, TypeAlias, TypeVar

from maya.api import OpenMaya as om

from ...node.modifier import ModifierManager
from ...node.nodes import Nodes

ParamsT = TypeVar("ParamsT")

CommandResult: TypeAlias = (
    bool | int | float | str | list[int] | list[float] | list[str]
)

class MPxCommandBase(om.MPxCommand, Generic[ParamsT]):
    COMMAND_NAME: ClassVar[str]

    def __new__(cls) -> Self: ...
    def __init__(self) -> None: ...
    @property
    def modifier_manager(self) -> ModifierManager: ...
    @property
    def nodes(self) -> Nodes: ...
    @classmethod
    def creator(cls) -> Self: ...
    @classmethod
    def create_syntax(cls) -> om.MSyntax: ...
    @abstractmethod
    def parse_arguments(self, arg_database: om.MArgDatabase) -> ParamsT: ...
    @abstractmethod
    def execute(self, params: ParamsT) -> CommandResult | None: ...
    def doIt(self, args: om.MArgList) -> None: ...
    def undoIt(self) -> None: ...
    def redoIt(self) -> None: ...
    def isUndoable(self) -> bool: ...
