# coding: utf-8
from __future__ import annotations

import argparse
import ast
import keyword
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class NodeDefinition:
    method_name: str
    node_type: str
    class_name: str
    module_name: str

    @property
    def can_import(self) -> bool:
        return all(
            not keyword.iskeyword(part)
            for part in self.module_name.lstrip(".").split(".")
        )

    @property
    def return_type(self) -> str:
        if self.can_import:
            return self.class_name
        return "NodeOperator"


def _find_node_definition(
    path: Path,
    node_dir: Path,
) -> NodeDefinition | None:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    definitions = []

    for statement in tree.body:
        if not isinstance(statement, ast.ClassDef):
            continue
        for class_statement in statement.body:
            if not isinstance(class_statement, ast.Assign):
                continue
            if not any(
                isinstance(target, ast.Name) and target.id == "NODE_TYPE"
                for target in class_statement.targets
            ):
                continue
            value = class_statement.value
            if not isinstance(value, ast.Constant) or not isinstance(
                value.value, str
            ):
                continue

            node_type = value.value
            method_name = (
                f"{node_type}_" if keyword.iskeyword(node_type) else node_type
            )
            if not method_name.isidentifier():
                raise ValueError(
                    f"nodeType cannot be exposed as a method: {node_type!r}"
                )

            relative_module = path.relative_to(node_dir).with_suffix("")
            module_name = "." + ".".join(relative_module.parts)
            definitions.append(
                NodeDefinition(
                    method_name=method_name,
                    node_type=node_type,
                    class_name=statement.name,
                    module_name=module_name,
                )
            )

    if not definitions:
        return None
    if len(definitions) > 1:
        raise ValueError(f"Multiple node classes found: {path}")
    return definitions[0]


def collect_node_definitions(python_root: Path) -> tuple[NodeDefinition, ...]:
    node_dir = python_root / "bd_util" / "maya" / "node"
    operator_dir = node_dir / "operator" / "node"
    package_dirs = (
        operator_dir / "dg",
        operator_dir / "dag",
        operator_dir / "dag" / "transform",
        operator_dir / "dag" / "shape",
    )

    definitions = []
    for package_dir in package_dirs:
        for path in sorted(package_dir.glob("*.py")):
            definition = _find_node_definition(path, node_dir)
            if definition is not None:
                definitions.append(definition)

    definitions.sort(key=lambda definition: definition.method_name)

    method_names = [definition.method_name for definition in definitions]
    if len(method_names) != len(set(method_names)):
        raise ValueError("Duplicate ExistingNode method names found")

    class_names = [definition.class_name for definition in definitions]
    if len(class_names) != len(set(class_names)):
        raise ValueError("Duplicate NodeOperator class names found")

    return tuple(definitions)


def generate_existing_node_stub_code(python_root: Path) -> str:
    definitions = collect_node_definitions(python_root)
    lines = [
        "# coding: utf-8",
        "# This file is generated by generate_existing_node_stub.py.",
        "from __future__ import annotations",
        "",
        "from maya.api import OpenMaya as om",
        "",
        "from .modifier import ModifierManager",
        "from .operator.node._core import NodeOperator",
    ]

    lines.extend(
        "from {} import {}".format(
            definition.module_name,
            definition.class_name,
        )
        for definition in definitions
        if definition.can_import
    )
    lines.extend(
        [
            "",
            "",
            "class ExistingNode:",
            "    def __new__(",
            "        cls,",
            "        node: str | om.MObject,",
            "        modifier_manager: ModifierManager | None = None,",
            "        auto_add_attr: bool = False,",
            "    ) -> NodeOperator: ...",
        ]
    )

    for definition in definitions:
        lines.extend(
            [
                "",
                "    @staticmethod",
                f"    def {definition.method_name}(",
                "        node: str | om.MObject,",
                "        modifier_manager: ModifierManager | None = None,",
                "        auto_add_attr: bool = False,",
                f"    ) -> {definition.return_type}: ...",
            ]
        )

    return "\n".join(lines) + "\n"


def existing_node_stub_path(python_root: Path) -> Path:
    return python_root / "bd_util" / "maya" / "node" / "existing_node.pyi"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    python_root = Path(__file__).resolve().parents[6]
    output_path = existing_node_stub_path(python_root)
    code = generate_existing_node_stub_code(python_root)

    if args.check:
        if not output_path.is_file() or output_path.read_text(
            encoding="utf-8"
        ) != code:
            raise SystemExit(
                f"ExistingNode stub is out of date: {output_path}"
            )
        return

    output_path.write_text(code, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
