# coding: utf-8
# This file is generated by generate_existing_node_stub.py.
from __future__ import annotations

from collections.abc import Callable

from ..modifier import ModifierManager
from ..operator.node._core import DEFAULT_VALUE_AUTO_ADD_ATTR, NodeOperator
from ..operator.node.dag._core import DAG
from ..operator.node.dag.shape._core import Shape
from ..operator.node.dag.transform._core import Transform
from ..operator.node.dag.shape.ai_area_light import AiAreaLight
from ..operator.node.dag.shape.ai_curve_collector import AiCurveCollector
from ..operator.node.dag.shape.ai_light_blocker import AiLightBlocker
from ..operator.node.dag.shape.ai_light_portal import AiLightPortal
from ..operator.node.dag.shape.ai_mesh_light import AiMeshLight
from ..operator.node.dag.shape.ai_photometric_light import AiPhotometricLight
from ..operator.node.dag.shape.ai_sky_dome_light import AiSkyDomeLight
from ..operator.node.dag.shape.ai_stand_in import AiStandIn
from ..operator.node.dag.shape.ai_volume import AiVolume
from ..operator.node.dag.shape.ambient_light import AmbientLight
from ..operator.node.dag.shape.angle_dimension import AngleDimension
from ..operator.node.dag.shape.annotation_shape import AnnotationShape
from ..operator.node.dag.shape.arc_length_dimension import ArcLengthDimension
from ..operator.node.dag.shape.area_light import AreaLight
from ..operator.node.dag.shape.base_lattice import BaseLattice
from ..operator.node.dag.shape.bezier_curve import BezierCurve
from ..operator.node.dag.shape.camera import Camera
from ..operator.node.dag.shape.cluster_flexor_shape import ClusterFlexorShape
from ..operator.node.dag.shape.cluster_handle import ClusterHandle
from ..operator.node.dag.shape.deform_bend import DeformBend
from ..operator.node.dag.shape.deform_flare import DeformFlare
from ..operator.node.dag.shape.deform_sine import DeformSine
from ..operator.node.dag.shape.deform_squash import DeformSquash
from ..operator.node.dag.shape.deform_twist import DeformTwist
from ..operator.node.dag.shape.deform_wave import DeformWave
from ..operator.node.dag.shape.directed_disc import DirectedDisc
from ..operator.node.dag.shape.directional_light import DirectionalLight
from ..operator.node.dag.shape.distance_dim_shape import DistanceDimShape
from ..operator.node.dag.shape.dropoff_locator import DropoffLocator
from ..operator.node.dag.shape.dyn_holder import DynHolder
from ..operator.node.dag.shape.dynamic_constraint import DynamicConstraint
from ..operator.node.dag.shape.environment_fog import EnvironmentFog
from ..operator.node.dag.shape.flexor_shape import FlexorShape
from ..operator.node.dag.shape.fluid_shape import FluidShape
from ..operator.node.dag.shape.fluid_texture2_d import FluidTexture2D
from ..operator.node.dag.shape.fluid_texture3_d import FluidTexture3D
from ..operator.node.dag.shape.follicle import Follicle
from ..operator.node.dag.shape.geo_connectable import GeoConnectable
from ..operator.node.dag.shape.grease_plane import GreasePlane
from ..operator.node.dag.shape.grease_plane_render_shape import (
    GreasePlaneRenderShape,
)
from ..operator.node.dag.shape.hair_constraint import HairConstraint
from ..operator.node.dag.shape.hair_system import HairSystem
from ..operator.node.dag.shape.height_field import HeightField
from ..operator.node.dag.shape.hik_floor_contact_marker import (
    HikFloorContactMarker,
)
from ..operator.node.dag.shape.image_plane import ImagePlane
from ..operator.node.dag.shape.implicit_box import ImplicitBox
from ..operator.node.dag.shape.implicit_cone import ImplicitCone
from ..operator.node.dag.shape.implicit_sphere import ImplicitSphere
from ..operator.node.dag.shape.lattice import Lattice
from ..operator.node.dag.shape.line_modifier import LineModifier
from ..operator.node.dag.shape.locator import Locator
from ..operator.node.dag.shape.mesh import Mesh
from ..operator.node.dag.shape.motion_trail_shape import MotionTrailShape
from ..operator.node.dag.shape.n_cloth import NCloth
from ..operator.node.dag.shape.n_particle import NParticle
from ..operator.node.dag.shape.n_rigid import NRigid
from ..operator.node.dag.shape.nurbs_curve import NurbsCurve
from ..operator.node.dag.shape.nurbs_surface import NurbsSurface
from ..operator.node.dag.shape.orientation_marker import OrientationMarker
from ..operator.node.dag.shape.param_dimension import ParamDimension
from ..operator.node.dag.shape.particle import Particle
from ..operator.node.dag.shape.pfx_hair import PfxHair
from ..operator.node.dag.shape.pfx_toon import PfxToon
from ..operator.node.dag.shape.point_light import PointLight
from ..operator.node.dag.shape.position_marker import PositionMarker
from ..operator.node.dag.shape.render_box import RenderBox
from ..operator.node.dag.shape.render_cone import RenderCone
from ..operator.node.dag.shape.render_rect import RenderRect
from ..operator.node.dag.shape.render_sphere import RenderSphere
from ..operator.node.dag.shape.rigid_body import RigidBody
from ..operator.node.dag.shape.sketch_plane import SketchPlane
from ..operator.node.dag.shape.snapshot_shape import SnapshotShape
from ..operator.node.dag.shape.soft_mod_handle import SoftModHandle
from ..operator.node.dag.shape.spot_light import SpotLight
from ..operator.node.dag.shape.spring import Spring
from ..operator.node.dag.shape.stereo_rig_camera import StereoRigCamera
from ..operator.node.dag.shape.stroke import Stroke
from ..operator.node.dag.shape.subdiv import Subdiv
from ..operator.node.dag.shape.ufe_proxy_camera_shape import (
    UfeProxyCameraShape,
)
from ..operator.node.dag.shape.volume_light import VolumeLight

class ShapeWithTransformCreator:
    def __init__(
        self,
        modifier_manager: ModifierManager,
        node_class_resolver: Callable[[str], type[NodeOperator]],
    ) -> None: ...
    @property
    def modifier_manager(self) -> ModifierManager: ...
    def create(
        self,
        node_name: str,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Shape]: ...
    def available_node_names(self) -> tuple[str, ...]: ...
    def __getattr__(
        self,
        node_name: str,
    ) -> Callable[..., tuple[Transform, Shape]]: ...
    def aiAreaLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiAreaLight]: ...
    def aiCurveCollector(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiCurveCollector]: ...
    def aiLightBlocker(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiLightBlocker]: ...
    def aiLightPortal(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiLightPortal]: ...
    def aiMeshLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiMeshLight]: ...
    def aiPhotometricLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiPhotometricLight]: ...
    def aiSkyDomeLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiSkyDomeLight]: ...
    def aiStandIn(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiStandIn]: ...
    def aiVolume(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AiVolume]: ...
    def ambientLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AmbientLight]: ...
    def angleDimension(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AngleDimension]: ...
    def annotationShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AnnotationShape]: ...
    def arcLengthDimension(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ArcLengthDimension]: ...
    def areaLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, AreaLight]: ...
    def baseLattice(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, BaseLattice]: ...
    def bezierCurve(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, BezierCurve]: ...
    def camera(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Camera]: ...
    def clusterFlexorShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ClusterFlexorShape]: ...
    def clusterHandle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ClusterHandle]: ...
    def deformBend(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DeformBend]: ...
    def deformFlare(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DeformFlare]: ...
    def deformSine(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DeformSine]: ...
    def deformSquash(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DeformSquash]: ...
    def deformTwist(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DeformTwist]: ...
    def deformWave(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DeformWave]: ...
    def directedDisc(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DirectedDisc]: ...
    def directionalLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DirectionalLight]: ...
    def distanceDimShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DistanceDimShape]: ...
    def dropoffLocator(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DropoffLocator]: ...
    def dynHolder(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DynHolder]: ...
    def dynamicConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, DynamicConstraint]: ...
    def environmentFog(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, EnvironmentFog]: ...
    def flexorShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, FlexorShape]: ...
    def fluidShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, FluidShape]: ...
    def fluidTexture2D(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, FluidTexture2D]: ...
    def fluidTexture3D(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, FluidTexture3D]: ...
    def follicle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Follicle]: ...
    def geoConnectable(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, GeoConnectable]: ...
    def greasePlane(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, GreasePlane]: ...
    def greasePlaneRenderShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, GreasePlaneRenderShape]: ...
    def hairConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, HairConstraint]: ...
    def hairSystem(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, HairSystem]: ...
    def heightField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, HeightField]: ...
    def hikFloorContactMarker(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, HikFloorContactMarker]: ...
    def imagePlane(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ImagePlane]: ...
    def implicitBox(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ImplicitBox]: ...
    def implicitCone(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ImplicitCone]: ...
    def implicitSphere(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ImplicitSphere]: ...
    def lattice(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Lattice]: ...
    def lineModifier(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, LineModifier]: ...
    def locator(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Locator]: ...
    def mesh(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Mesh]: ...
    def motionTrailShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, MotionTrailShape]: ...
    def nCloth(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, NCloth]: ...
    def nParticle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, NParticle]: ...
    def nRigid(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, NRigid]: ...
    def nurbsCurve(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, NurbsCurve]: ...
    def nurbsSurface(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, NurbsSurface]: ...
    def orientationMarker(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, OrientationMarker]: ...
    def paramDimension(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, ParamDimension]: ...
    def particle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Particle]: ...
    def pfxHair(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, PfxHair]: ...
    def pfxToon(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, PfxToon]: ...
    def pointLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, PointLight]: ...
    def positionMarker(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, PositionMarker]: ...
    def renderBox(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, RenderBox]: ...
    def renderCone(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, RenderCone]: ...
    def renderRect(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, RenderRect]: ...
    def renderSphere(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, RenderSphere]: ...
    def rigidBody(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, RigidBody]: ...
    def sketchPlane(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, SketchPlane]: ...
    def snapshotShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, SnapshotShape]: ...
    def softModHandle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, SoftModHandle]: ...
    def spotLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, SpotLight]: ...
    def spring(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Spring]: ...
    def stereoRigCamera(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, StereoRigCamera]: ...
    def stroke(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Stroke]: ...
    def subdiv(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, Subdiv]: ...
    def ufeProxyCameraShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, UfeProxyCameraShape]: ...
    def volumeLight(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        shape_name: str | None = None,
        parent: DAG | None = None,
    ) -> tuple[Transform, VolumeLight]: ...
