# coding: utf-8
# This file is generated by generate_existing_node_stub.py.
from __future__ import annotations

from ..operator.node._core import DEFAULT_VALUE_AUTO_ADD_ATTR
from ..operator.node.dag.transform.aim_constraint import AimConstraint
from ..operator.node.dag.transform.air_field import AirField
from ..operator.node.dag.transform.clip_ghost_shape import ClipGhostShape
from ..operator.node.dag.transform.collision_model import CollisionModel
from ..operator.node.dag.transform.curve_var_group import CurveVarGroup
from ..operator.node.dag.transform.dag_container import DagContainer
from ..operator.node.dag.transform.drag_field import DragField
from ..operator.node.dag.transform.fluid_emitter import FluidEmitter
from ..operator.node.dag.transform.foster_parent import FosterParent
from ..operator.node.dag.transform.geometry_constraint import (
    GeometryConstraint,
)
from ..operator.node.dag.transform.geometry_var_group import GeometryVarGroup
from ..operator.node.dag.transform.gravity_field import GravityField
from ..operator.node.dag.transform.hik_effector import HikEffector
from ..operator.node.dag.transform.hik_fk_joint import HikFKJoint
from ..operator.node.dag.transform.hik_ground_plane import HikGroundPlane
from ..operator.node.dag.transform.hik_handle import HikHandle
from ..operator.node.dag.transform.hik_ik_effector import HikIKEffector
from ..operator.node.dag.transform.ik_effector import IkEffector
from ..operator.node.dag.transform.ik_handle import IkHandle
from ..operator.node.dag.transform.instancer import Instancer
from ..operator.node.dag.transform.joint import Joint
from ..operator.node.dag.transform.lod_group import LodGroup
from ..operator.node.dag.transform.look_at import LookAt
from ..operator.node.dag.transform.mesh_var_group import MeshVarGroup
from ..operator.node.dag.transform.newton_field import NewtonField
from ..operator.node.dag.transform.normal_constraint import NormalConstraint
from ..operator.node.dag.transform.nucleus import Nucleus
from ..operator.node.dag.transform.old_normal_constraint import (
    OldNormalConstraint,
)
from ..operator.node.dag.transform.old_tangent_constraint import (
    OldTangentConstraint,
)
from ..operator.node.dag.transform.orient_constraint import OrientConstraint
from ..operator.node.dag.transform.parent_constraint import ParentConstraint
from ..operator.node.dag.transform.place3d_texture import Place3dTexture
from ..operator.node.dag.transform.point_constraint import PointConstraint
from ..operator.node.dag.transform.point_emitter import PointEmitter
from ..operator.node.dag.transform.point_on_poly_constraint import (
    PointOnPolyConstraint,
)
from ..operator.node.dag.transform.pole_vector_constraint import (
    PoleVectorConstraint,
)
from ..operator.node.dag.transform.primitive_falloff import PrimitiveFalloff
from ..operator.node.dag.transform.radial_field import RadialField
from ..operator.node.dag.transform.rigid_constraint import RigidConstraint
from ..operator.node.dag.transform.scale_constraint import ScaleConstraint
from ..operator.node.dag.transform.subdiv_surface_var_group import (
    SubdivSurfaceVarGroup,
)
from ..operator.node.dag.transform.surface_var_group import SurfaceVarGroup
from ..operator.node.dag.transform.symmetry_constraint import (
    SymmetryConstraint,
)
from ..operator.node.dag.transform.tangent_constraint import TangentConstraint
from ..operator.node.dag.transform.texture_deformer_handle import (
    TextureDeformerHandle,
)
from ..operator.node.dag.transform._core import Transform
from ..operator.node.dag.transform.turbulence_field import TurbulenceField
from ..operator.node.dag.transform.ufe_proxy_transform import UfeProxyTransform
from ..operator.node.dag.transform.uniform_field import UniformField
from ..operator.node.dag.transform.unknown_transform import UnknownTransform
from ..operator.node.dag.transform.volume_axis_field import VolumeAxisField
from ..operator.node.dag.transform.vortex_field import VortexField

class _TransformNodeCreatorMixin:
    def aimConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> AimConstraint: ...
    def airField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> AirField: ...
    def clipGhostShape(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> ClipGhostShape: ...
    def collisionModel(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> CollisionModel: ...
    def curveVarGroup(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> CurveVarGroup: ...
    def dagContainer(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> DagContainer: ...
    def dragField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> DragField: ...
    def fluidEmitter(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> FluidEmitter: ...
    def fosterParent(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> FosterParent: ...
    def geometryConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> GeometryConstraint: ...
    def geometryVarGroup(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> GeometryVarGroup: ...
    def gravityField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> GravityField: ...
    def hikEffector(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> HikEffector: ...
    def hikFKJoint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> HikFKJoint: ...
    def hikGroundPlane(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> HikGroundPlane: ...
    def hikHandle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> HikHandle: ...
    def hikIKEffector(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> HikIKEffector: ...
    def ikEffector(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> IkEffector: ...
    def ikHandle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> IkHandle: ...
    def instancer(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> Instancer: ...
    def joint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> Joint: ...
    def lodGroup(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> LodGroup: ...
    def lookAt(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> LookAt: ...
    def meshVarGroup(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> MeshVarGroup: ...
    def newtonField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> NewtonField: ...
    def normalConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> NormalConstraint: ...
    def nucleus(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> Nucleus: ...
    def oldNormalConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> OldNormalConstraint: ...
    def oldTangentConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> OldTangentConstraint: ...
    def orientConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> OrientConstraint: ...
    def parentConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> ParentConstraint: ...
    def place3dTexture(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> Place3dTexture: ...
    def pointConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> PointConstraint: ...
    def pointEmitter(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> PointEmitter: ...
    def pointOnPolyConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> PointOnPolyConstraint: ...
    def poleVectorConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> PoleVectorConstraint: ...
    def primitiveFalloff(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> PrimitiveFalloff: ...
    def radialField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> RadialField: ...
    def rigidConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> RigidConstraint: ...
    def scaleConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> ScaleConstraint: ...
    def subdivSurfaceVarGroup(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> SubdivSurfaceVarGroup: ...
    def surfaceVarGroup(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> SurfaceVarGroup: ...
    def symmetryConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> SymmetryConstraint: ...
    def tangentConstraint(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> TangentConstraint: ...
    def textureDeformerHandle(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> TextureDeformerHandle: ...
    def transform(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> Transform: ...
    def turbulenceField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> TurbulenceField: ...
    def ufeProxyTransform(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> UfeProxyTransform: ...
    def uniformField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> UniformField: ...
    def unknownTransform(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> UnknownTransform: ...
    def volumeAxisField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> VolumeAxisField: ...
    def vortexField(
        self,
        name: str | None = None,
        auto_add_attr: bool = DEFAULT_VALUE_AUTO_ADD_ATTR,
        *,
        parent: Transform | None = None,
    ) -> VortexField: ...
